import {PageSchema} from "@/components/constructor/page-render/types";
import {COMPANY_NAME} from "@/resources/constants";

const deliveryPolicyEn: PageSchema = {
    meta: {
        title: `Service Delivery, Revisions and Complaints Policy – ${COMPANY_NAME}`,
        description: "This Policy explains delivery estimates, file requirements, revisions and the complaint process for AI and Human Translation.",
        canonical: "/delivery-policy",
        ogImage: {
            title: `Service Delivery, Revisions and Complaints Policy – ${COMPANY_NAME}`,
            description: "This Policy explains delivery estimates, file requirements, revisions and the complaint process for AI and Human Translation.",
            bg: "#170B33",
            color: "#ffffff",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Service Delivery, Revisions and Complaints Policy",
            description: "Last updated: 19 August 2026",
        },
        {
            type: "text",
            description: "This Policy explains delivery estimates, file requirements, revisions and the complaint process for AI and Human Translation.",
        },
        {
            type: "text",
            title: "Service Selection and Confirmation",
            description: "Selection. Before confirming an Order, the user selects AI Translation or Human Translation and reviews the source language, target language, price, calculated volume and estimated delivery time.",
        },
        {
            type: "text",
            description: "Confirmation. The user is responsible for confirming that the correct file and languages have been selected. An Order confirmation records the accepted scope.",
        },
        {
            type: "text",
            description: "Clarifications. QueTranslations may request clarification where instructions, terminology, formatting or file content are ambiguous. Delivery timing may pause until the user provides a usable response.",
        },
        {
            type: "text",
            title: "AI Translation Delivery",
            description: "Expected timing. AI Translation is normally generated and delivered within several minutes. Actual time depends on file size, extraction, format conversion, model availability, system load and security review.",
        },
        {
            type: "text",
            description: "No guaranteed minute count. The estimate is not a fixed service-level guarantee. QueTranslations will not treat a short technical delay by itself as non-performance where the Order is completed within a reasonable period.",
        },
        {
            type: "text",
            description: "Automated output. AI Translation is not human-reviewed unless expressly purchased as a separate Human Translation service. Users must review AI output before external use or reliance.",
        },
        {
            type: "text",
            title: "Human Translation Delivery",
            description: "Standard volume. Human Translation containing no more than 5,000 source words is normally delivered within 24 to 48 hours after Order confirmation.",
        },
        {
            type: "text",
            description: "Factors affecting timing. The applicable point within that range depends on source-word count, language pair, complexity, formatting, file quality, instructions and translator availability.",
        },
        {
            type: "text",
            description: "Orders over 5,000 words. A separate estimated delivery time will be displayed or communicated before confirmation. The user must accept that estimate before work begins, and the standard 24-to-48-hour period does not apply.",
        },
        {
            type: "text",
            description: "Volume measurement. The source-word count generated by the Services is used for pricing and delivery estimates unless a manifest extraction error is identified. Images, scans, tables, footnotes and non-editable text may require additional processing.",
        },
        {
            type: "text",
            title: "File Requirements",
            description: "Usable files. Files must be complete, legible, free from malware and provided in a supported format. Password-protected, corrupted, low-resolution or handwritten materials may be refused or require a revised estimate.",
        },
        {
            type: "text",
            description: "Formatting. QueTranslations will use reasonable efforts to preserve basic formatting where the selected format supports it. Exact reproduction of complex layouts, fonts, graphics, pagination, tracked changes or embedded objects is not guaranteed unless expressly included in the Order.",
        },
        {
            type: "text",
            description: "Source changes. Text added or changed after confirmation is outside the original scope and may require a new Order, additional charge or revised delivery estimate.",
        },
        {
            type: "text",
            title: "Delivery Method and Completion",
            description: "Electronic delivery. Completed translations are delivered through the Account, by email or through another digital method identified in the Order flow.",
        },
        {
            type: "text",
            description: "Completion. An Order is treated as delivered when the file or output is made available through the agreed electronic method, provided the user can reasonably access it.",
        },
        {
            type: "text",
            description: "User responsibility. Users should maintain current contact information, monitor the Account and download important files. QueTranslations is not responsible for loss caused solely by an incorrect user email address, ignored notification or failure to download before a disclosed deletion date.",
        },
        {
            type: "text",
            title: "Delays",
            description: "User-caused delay. Delivery estimates extend reasonably where the user provides incomplete files, changes instructions, fails to respond, does not provide required access or otherwise prevents performance.",
        },
        {
            type: "text",
            description: "Operational delay. QueTranslations may experience delay due to model or infrastructure outages, cyber incidents, translator illness or unavailability, unusual language complexity, force majeure or other events beyond reasonable control.",
        },
        {
            type: "text",
            description: "Notice and remedy. Where a material delay is identified, QueTranslations will use reasonable efforts to notify the user and provide a revised estimate. If the revised timing is unacceptable and the service has not been fully performed, the user may request cancellation subject to payment for work already provided and mandatory consumer rights.",
        },
        {
            type: "text",
            title: "Revisions",
            description: "Eligible Human Translation corrections. A correction is available for a substantiated mistranslation, omission, grammatical error or failure to follow an instruction included in the confirmed Human Translation Order.",
        },
        {
            type: "text",
            description: "Excluded changes. A free correction does not include new source text, a different target language, changed terminology supplied after delivery, subjective stylistic preferences not stated in advance, or reformatting outside the agreed scope.",
        },
        {
            type: "text",
            description: "AI output. AI output may vary when rerun. QueTranslations may rerun a technically defective AI Order but does not promise human-level revision within the AI Translation price.",
        },
        {
            type: "text",
            description: "Prompt notice. Users are encouraged to request correction within seven days after delivery so that the assigned context remains available. Longer mandatory consumer claim periods remain unaffected.",
        },
        {
            type: "text",
            title: "Complaints",
            description: "Required information. A complaint should include the Account email, Order identifier, source and translated passages, a concise description of the issue and the remedy requested.",
        },
        {
            type: "text",
            description: "Assessment. QueTranslations may compare the source, instructions and deliverable, consult the assigned translator, review technical logs and request additional context.",
        },
        {
            type: "text",
            description: "Response period. Written consumer complaints will be answered within 15 days. If a complex technical or linguistic review requires more time, QueTranslations will explain the status where permitted by applicable law.",
        },
        {
            type: "text",
            description: "Available outcomes. Depending on the issue, QueTranslations may correct or rerun the translation, deliver a missing file, restore Balance, reduce the price, issue a refund or explain why the deliverable conforms to the Order.",
        },
        {
            type: "text",
            title: "Limitations of Service",
            description: "No certified service. QueTranslations does not provide certified, sworn or notarised translations and does not warrant acceptance by courts, immigration authorities, registries, universities or other official bodies.",
        },
        {
            type: "text",
            description: "No professional legal or medical service. QueTranslations does not offer legal or medical translation as a regulated professional service. Users must obtain qualified professional review before using any translation in a legal, medical, clinical or safety-critical context.",
        },
        {
            type: "text",
            description: "Final review. The user remains responsible for names, numbers, dates, technical terms, formatting and suitability before publishing, submitting or relying on a translation.",
        },
        {
            type: "text",
            title: "Contact",
            description: "Service contact. Delivery questions, correction requests and complaints should be sent to info@quetranslations.com.",
        },
    ],
};

export default deliveryPolicyEn;
